on: [push]
name: Azure ARM
jobs:
  development:
    runs-on: ubuntu-latest
    environment: development
    steps:
      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
    - name: Run Development Deployment
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./master.template.json
        parameters: ./master.parameters.json ApimServiceName=apim-westjet-dev
        
  staging:
    needs: [development]
    runs-on: ubuntu-latest
    environment: staging
    steps:
      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template        
    - name: Run Staging Deployment
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./master.template.json
        parameters: ./master.parameters.json ApimServiceName=apim-wesjet-staging
